#! /usr/bin/env python3

from setuptools import setup

setup(name="python-laser-control",
      version="0.0.3",
      description="Laser Control Protocol",
      url="https://github.com/RAA80/python-laser-control",
      author="Alexey Ryadno",
      author_email="aryadno@mail.ru",
      license="MIT",
      packages=["laser"],
      scripts=["scripts/laser-console",
               "scripts/laser-gui",
               "scripts/laser-simulator"],
      install_requires=["pyserial >= 3.4"],
      platforms=["Linux", "Windows"],
      classifiers=["Development Status :: 3 - Alpha",
                   "Intended Audience :: Science/Research",
                   "Intended Audience :: Developers",
                   "License :: OSI Approved :: MIT License",
                   "Operating System :: Microsoft :: Windows",
                   "Operating System :: POSIX :: Linux",
                   "Operating System :: POSIX",
                   "Programming Language :: Python :: 3",
                   "Programming Language :: Python :: 3.9",
                   "Programming Language :: Python :: 3.10",
                   "Programming Language :: Python :: 3.11",
                  ],
     )
