#! /usr/bin/env python3

import argparse
import logging

import laser.device
from laser.client import LaserSerialClient, LaserTcpClient, LaserUdpClient

if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                     description="Laser Control Protocol command-line option",
                                     epilog="Usage example:\n"
                                            "laser-console --device RFL_C3000S --method TCP --address '127.0.0.1:10001' --send MPWROFF\n"
                                            "laser-console --device RFL_C3000S --method UDP --address '127.0.0.1:8099' --send SUT 10\n"
                                            "laser-console --device RFL_C3000S --method SERIAL --address 'COM1' --baudrate 9600 --send RUT")

    parser.add_argument("--device", type=str, required=True,
                                    help="device name (see device.py)")
    parser.add_argument("--method", type=str, choices=["SERIAL", "TCP", "UDP"],
                                    required=True, help="factory method")
    parser.add_argument("--address", type=str, required=True,
                                     help="serial port or IP:PORT address")
    parser.add_argument("--baudrate", type=int, default=9600,
                                      help="serial port baudrate")
    parser.add_argument("--send", type=str, nargs="+", metavar=("CMD", "VALUE"),
                                  required=True, help="send CMD with value")
    parser.add_argument("--debug", action="store_true",
                                   help="print debug information")
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    device = getattr(laser.device, args.device)

    if args.method == "SERIAL":
        client = LaserSerialClient(device=device, address=args.address, baudrate=args.baudrate)
    elif args.method == "TCP":
        client = LaserTcpClient(device=device, address=args.address)
    elif args.method == "UDP":
        client = LaserUdpClient(device=device, address=args.address)

    if args.send:
        cmd = args.send[0]
        try:
            value = args.send[1]
        except IndexError:
            value = None

        print(client.send(cmd, value))
